from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_pdf(
    filename,
    name,
    email,
    ats_score,
    interview_score,
    question_scores,
    recommendation
):

    doc = SimpleDocTemplate(
        filename,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    content = []

    # ----------------------------------
    # Title
    # ----------------------------------

    content.append(
        Paragraph(
            "<b>AI Mock Interview System</b>",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "<b>Candidate Evaluation Report</b>",
            styles["Heading2"]
        )
    )

    content.append(Spacer(1, 15))

    # ----------------------------------
    # Report Date
    # ----------------------------------

    current_date = datetime.now().strftime("%d-%m-%Y %H:%M")

    content.append(
        Paragraph(
            f"<b>Report Generated:</b> {current_date}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 15))

    # ----------------------------------
    # Candidate Details
    # ----------------------------------

    content.append(
        Paragraph(
            "<b>Candidate Details</b>",
            styles["Heading2"]
        )
    )

    details = [
        ["Candidate Name", name],
        ["Email", email],
        ["ATS Resume Score", f"{ats_score}/100"],
        ["Interview Score", f"{interview_score}/10"]
    ]

    table = Table(details, colWidths=[170, 300])

    table.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("TOPPADDING", (0, 0), (-1, -1), 8),

            ]

        )

    )

    content.append(table)

    content.append(Spacer(1, 20))

    # ----------------------------------
    # Question Scores
    # ----------------------------------

    content.append(
        Paragraph(
            "<b>Question-wise Interview Performance</b>",
            styles["Heading2"]
        )
    )

    score_table = [["Question", "Score"]]

    for i, score in enumerate(question_scores):

        score_table.append(
            [
                f"Question {i+1}",
                f"{score}/10"
            ]
        )

    table2 = Table(score_table, colWidths=[220, 120])

    table2.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.grey),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ]

        )

    )

    content.append(table2)

    content.append(Spacer(1, 20))

    # ----------------------------------
    # Recommendation
    # ----------------------------------

    content.append(
        Paragraph(
            "<b>AI Recommendation</b>",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            recommendation,
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # ----------------------------------
    # Footer
    # ----------------------------------

    content.append(
        Paragraph(
            "<b>Generated by AI Mock Interview System v1.0</b>",
            styles["Normal"]
        )
    )

    doc.build(content)